var lyrics = [
  { time: 51, text: "Sekedar berandai" },
  { time: 54, text: "Menatapi diri ini" },
  { time: 60, text: "Berpencar pergi 'tuk mencari" },
  { time: 65, text: "Apa yang lama dicari" },
  { time: 71, text: "Pergi tanpa pamrih" },
  { time: 74, text: "Pergi tanpa pamit akan" },
  { time: 80, text: "Ke sana-kemari tanpa arah" },
  { time: 84, text: "Serta ratusan makian" },
  { time: 90, text: "Kembali pulang" },
  { time: 96, text: "'Tuk menenangi" },
  { time: 101, text: "Banyaknya luka yang berantakan" },
  { time: 106, text: "Peluk hangat, sigap 'tuk sembuhkan" },
  { time: 111, text: "Kembali pulang" },
  { time: 116, text: "Bersama terang" },
  { time: 121, text: "Menghiasi diri, merayakan" },
  { time: 126, text: "Genggaman tangan yang masih ada" },
  { time: 176, text: "Kembali pulang" },
  { time: 180, text: "'Tuk menenangi" },
  { time: 185, text: "Banyaknya luka yang berantakan" },
  { time: 190, text: "Peluk hangat, sigap 'tuk sembuhkan" },
  { time: 196, text: "Kembali pulang" },
  { time: 200, text: "Bersama terang" },
  { time: 205, text: "Menghiasi diri, merayakan" },
  { time: 211, text: "Genggaman tangan yang masih ada" }
];