var lyrics = [
  { time: 1, text: "Yang kau dengar dalam hati" },
  { time: 2, text: "Biarlah bergema kali ini" },
  { time: 3, text: "Jangan kau redam dan" },
  { time: 4, text: "Yang kau tempa sejauh ini" },
  { time: 5, text: "Jangan kau anggap tak berguna" },
  { time: 6, text: "Hanya kau yang tahu" },
  { time: 7, text: "Semua pengorbananmu" },
  { time: 8, text: "'Tuk hal yang kau cinta" },
  { time: 9, text: "Tanyakan pada dirimu" },
  { time: 10, text: "Sebetapa kau mau" },
  { time: 11, text: "Oh, 'tuk mengubah hidupmu" },
  { time: 12, text: "Di tanganmu, kuasa" },
  { time: 13, text: "Atas ceritamu, sekarang juga" },
  { time: 14, text: "Besok atau hari ini" },
  { time: 15, text: "Kau yang pegang kendali" },
  { time: 16, text: "Di tanganmu, kuasa" },
  { time: 17, text: "Atas ceritamu, sekarang juga" },
  { time: 18, text: "Berbagai cobaan dan hal yang buat kau ragu" },
  { time: 19, text: "Jadikan percikan 'tuk menerpa tekadmu" },
  { time: 20, text: "Jalan hidupmu hanya milikmu sendiri" },
  { time: 21, text: "Rasakan nikmatnya hidupmu hari ini" },
  { time: 22, text: "Berbagai cobaan dan hal yang buat kau ragu" },
  { time: 23, text: "Jadikan percikan 'tuk menerpa tekadmu" },
  { time: 24, text: "Jalan hidupmu hanya milikmu sendiri" },
  { time: 25, text: "Rasakan nikmatnya hidupmu hari ini" },
  { time: 26, text: "Berbagai cobaan dan hal yang buat kau ragu" },
  { time: 27, text: "Jadikan percikan 'tuk menerpa tekadmu" },
  { time: 28, text: "Jalan hidupmu hanya milikmu sendiri" },
  { time: 29, text: "Rasakan nikmatnya hidupmu hari ini" }
];