var lyrics = [
  { time: 0, text: "Di seluruh tempat di seluruh dunia" },
  { time: 4, text: "Dimanapun lagu cinta ini terputar" },
  { time: 8, text: "Aku bergeleng kecil dan tersenyum tipis" },
  { time: 12, text: "Andai lagu ini tertulis olehku" },
  { time: 16, text: "Direkam yang manis diisi bombastis" },
  { time: 20, text: "Ditujukan secara spesifik untukmu" },
  { time: 24, text: "Tentang hal-hal yang hanya kita berdua tahu" },
  { time: 28, text: "Karena semua lagu cinta terdengar sama" },
  { time: 32, text: "Ha ha ha ha ha ha ha" },
  { time: 36, text: "Semua membosankan semua menjemukan" },
  { time: 40, text: "Tak ada yang bisa gambarkan parasmu" },
  { time: 44, text: "Secara sempurna maka kan kucoba" },
  { time: 48, text: "Karena semua yang lain terdengar sama" },
  { time: 52, text: "Terdengar sama" },
  { time: 56, text: "Semua membosankan semua menjemukan" },
  { time: 60, text: "Tak ada yang bisa gambarkan parasmu oh oh" },
  { time: 64, text: "Secara sempurna maka kan kucoba" },
  { time: 68, text: "Karena semua yang lain terdengar sama" },
  { time: 72, text: "Di seluruh tempat di seluruh dunia" },
  { time: 76, text: "Di mana pun lagu cinta ini terputar (terdengar sama)" },
  { time: 80, text: "Ada film di kepalaku yang kuputar" },
  { time: 84, text: "Adegan romantis pemerannya kamu" },
  { time: 88, text: "Di seluruh tempat di seluruh dunia" },
  { time: 92, text: "Di mana pun lagu cinta ini terputar" },
  { time: 96, text: "Ada film di kepalaku yang kuputar" },
  { time: 100, text: "Adegan romantis pemerannya kamu" },
  { time: 104, text: "Semua membosankan semua menjemukan" },
  { time: 108, text: "Tak ada yang bisa gambarkan parasmu" },
  { time: 112, text: "Secara sempurna maka kan kucoba" },
  { time: 116, text: "Karena semua yang lain terdengar sama" },
  { time: 120, text: "Terdengar sama" },
  { time: 124, text: "Terdengar sama" },
  { time: 3, text: "Terdengar sama" }
];